# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15xUsIc96lG4x4uuG39sa5PhoT7xVnVjz
"""

# app.py
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from datetime import datetime, timedelta
from typing import List, Optional, Dict
import requests
import pandas as pd
import joblib
import random
from collections import Counter

# =====================================================
# 1. OpenWeather 설정 (🔑 여기 API 키 직접 넣기)
# =====================================================
OWM_API_KEY = "9f8737894290204a7b2793f510443e46"  # <-- 네 OpenWeather API Key

OWM_GEOCODING_URL = "http://api.openweathermap.org/geo/1.0/direct"
OWM_FORECAST_URL = "https://api.openweathermap.org/data/2.5/forecast"  # 5일 / 3시간 예보
OWM_AIR_POLLUTION_URL = "http://api.openweathermap.org/data/2.5/air_pollution"

# =====================================================
# 2. FastAPI & CORS 설정
# =====================================================
app = FastAPI(
    title="AI 기반 실시간 날씨 & 맞춤 운동 추천 API",
    description="OpenWeather + XGBoost + 사용자 선호도를 이용한 운동 추천 서비스",
    version="1.0.0",
)

origins = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://144.24.73.5:8080",  # 팀 서버
    "http://144.24.73.5",
    # "https://프론트엔드-도메인주소"  # 실제 배포 프론트 있으면 추가
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# =====================================================
# 3. 모델 & 데이터 로딩
# =====================================================
# category_model.pkl / feature_scaler.pkl / category_label_encoder.pkl
category_model = joblib.load("category_model.pkl")
scaler = joblib.load("feature_scaler.pkl")
le_category = joblib.load("category_label_encoder.pkl")

# 활동 정보
activity_df = pd.read_csv("activity_information.csv")

activity_df = activity_df.rename(
    columns={
        "활동명": "activity_name",
        "활동카테고리": "category",
        "장소유형": "location_type",
        "난이도": "difficulty",
        "추천계절": "season",
        "적합시간대": "time_range",
    }
)

# 활동명 → 카테고리 매핑 (선호운동 → 카테고리 계산용)
activity_to_category: Dict[str, str] = {
    row["activity_name"]: row["category"]
    for _, row in activity_df.iterrows()
}

# =====================================================
# 4. 유틸 함수들 (계절, 시간대, 공기질 등)
# =====================================================
def get_season_from_month(m: int) -> str:
    if 3 <= m <= 5:
        return "봄"
    if 6 <= m <= 8:
        return "여름"
    if 9 <= m <= 11:
        return "가을"
    return "겨울"


def get_time_range_from_hour(h: int) -> str:
    if 5 <= h < 12:
        return "오전"
    if 12 <= h < 18:
        return "오후"
    if 18 <= h < 23:
        return "저녁"
    return "야간"


def grade_pm(pm10: float, pm25: float) -> str:
    """
    한국 환경 기준 대략 참고해서 등급 문자열 리턴
    """
    # 아주 거칠게 둘 중 더 나쁜 등급 기준 사용
    grade_score = 0  # 0: 좋음, 1: 보통, 2: 나쁨, 3: 매우 나쁨

    if pm10 > 150 or pm25 > 75:
        grade_score = 3
    elif pm10 > 80 or pm25 > 35:
        grade_score = 2
    elif pm10 > 30 or pm25 > 15:
        grade_score = 1
    else:
        grade_score = 0

    if grade_score == 0:
        return "좋음"
    if grade_score == 1:
        return "보통"
    if grade_score == 2:
        return "나쁨"
    return "매우 나쁨"


# =====================================================
# 5. OpenWeather Geocoding & Forecast & Air Pollution
# =====================================================
def geocode_owm(location_name: str):
    """
    한글 지명을 OpenWeather Geocoding으로 위/경도 변환
    1) "성남시 수정구,KR"
    2) "성남시 수정구"
    순서로 시도
    """
    for q in (f"{location_name},KR", location_name):
        params = {"q": q, "limit": 1, "appid": OWM_API_KEY}
        r = requests.get(OWM_GEOCODING_URL, params=params)
        r.raise_for_status()
        data = r.json()
        if data:
            lat = data[0]["lat"]
            lon = data[0]["lon"]
            return lat, lon

    raise ValueError(f"'{location_name}' 에 대한 좌표를 찾지 못했습니다. (OpenWeatherMap Geocoding)")


def get_forecast_from_owm(lat: float, lon: float, target_dt: datetime):
    """
    5일 / 3시간 예보에서 target_dt에 가장 가까운 한 개의 예보를 선택
    """
    params = {
        "lat": lat,
        "lon": lon,
        "appid": OWM_API_KEY,
        "units": "metric",
        "lang": "kr",
    }
    r = requests.get(OWM_FORECAST_URL, params=params)
    r.raise_for_status()
    data = r.json()
    forecasts = data.get("list", [])

    if not forecasts:
        # 예보가 없으면 대충 기본값
        return {
            "temperature": 15.0,
            "humidity": 50.0,
            "wind_speed": 1.5,
            "precipitation": 0.0,
            "owm_dt_txt": None,
        }

    # target_dt 와 가장 가까운 시간대의 예보 찾기
    best_item = None
    best_diff = None
    for item in forecasts:
        dt_txt = item.get("dt_txt")  # "2025-11-07 09:00:00" 같은 문자열
        if not dt_txt:
            continue
        f_dt = datetime.strptime(dt_txt, "%Y-%m-%d %H:%M:%S")
        diff = abs((f_dt - target_dt).total_seconds())
        if (best_diff is None) or (diff < best_diff):
            best_diff = diff
            best_item = item

    if best_item is None:
        best_item = forecasts[0]

    main = best_item.get("main", {})
    wind = best_item.get("wind", {})
    rain = best_item.get("rain", {})

    temp = main.get("temp", 15.0)
    hum = main.get("humidity", 50.0)
    ws = wind.get("speed", 1.5)
    precip = rain.get("3h", 0.0)

    return {
        "temperature": float(temp),
        "humidity": float(hum),
        "wind_speed": float(ws),
        "precipitation": float(precip),
        "owm_dt_txt": best_item.get("dt_txt"),
    }


def get_air_pollution_from_owm(lat: float, lon: float):
    """
    OpenWeather Air Pollution API 사용해서 PM10 / PM2.5 가져오기
    """
    params = {
        "lat": lat,
        "lon": lon,
        "appid": OWM_API_KEY,
    }
    r = requests.get(OWM_AIR_POLLUTION_URL, params=params)
    r.raise_for_status()
    data = r.json()
    lst = data.get("list", [])
    if not lst:
        return 0.0, 0.0

    comps = lst[0].get("components", {})
    pm10 = float(comps.get("pm10", 0.0))
    pm25 = float(comps.get("pm2_5", 0.0))
    return pm10, pm25


# =====================================================
# 6. Pydantic 요청 스키마
# =====================================================
class RecommendRequest(BaseModel):
    user_id: str
    location_name: str
    target_datetime: datetime
    favorites: Optional[List[str]] = None  # 실시간 입력 선호운동 2개 정도


# =====================================================
# 7. 메인 엔드포인트
# =====================================================
@app.get("/")
def home():
    return {"message": "AI 기반 실시간 날씨 & 맞춤 운동 추천 API 작동 중!"}


@app.post("/recommend/by-location-and-user")
def recommend_by_location_and_user(req: RecommendRequest):
    """
    - 위치 이름 + 시간 + 선호운동 리스트(favorites)를 받아서
    - OpenWeather에서 날씨 & 미세먼지 정보 조회
    - XGBoost로 카테고리 예측
    - 선호운동 & 날씨 & 공기질을 종합해 최종 카테고리 선택
    - 그 카테고리 안에서 선호운동을 우선적으로 운동명 추천
    """

    # 1) 선호운동 문자열 전처리
    raw_favorites = req.favorites or []
    favorites_clean = []
    for f in raw_favorites:
        # 뒤에 붙은 쉼표/공백 제거
        name = f.replace(",", " ").strip()
        if name:
            favorites_clean.append(name)

    # 2) 위치 → 위/경도
    lat, lon = geocode_owm(req.location_name)

    # 3) 날씨 예보 + 공기질
    target_dt = req.target_datetime
    forecast = get_forecast_from_owm(lat, lon, target_dt)
    pm10, pm25 = get_air_pollution_from_owm(lat, lon)
    pm_grade = grade_pm(pm10, pm25)

    # 4) 계절 / 시간대
    season_str = get_season_from_month(target_dt.month)
    time_range_str = get_time_range_from_hour(target_dt.hour)
    season_code = {"봄": 0, "여름": 1, "가을": 2, "겨울": 3}.get(season_str, -1)

    # 5) 모델 입력 만들기
    #    👉 학습때 사용한 feature 순서와 동일해야 함
    numeric_cols = ["temperature", "humidity", "wind_speed", "precipitation", "pm25", "pm10"]
    raw_numeric = [
        forecast["temperature"],
        forecast["humidity"],
        forecast["wind_speed"],
        forecast["precipitation"],
        pm25,
        pm10,
    ]
    scaled = scaler.transform([raw_numeric])[0]  # shape: (n_features,)
    X_input = pd.DataFrame([scaled], columns=numeric_cols)
    X_input["season_code"] = season_code

    # 6) XGBoost로 환경 기반 카테고리 예측
    pred_cat_id = category_model.predict(X_input)[0]
    env_category = le_category.inverse_transform([pred_cat_id])[0]

    # 7) 공기질 기반 추천 카테고리(실내/실외) 경향
    pm_preferred_category: Optional[str] = None
    if pm_grade in ["나쁨", "매우 나쁨"]:
        pm_preferred_category = "피트니스"  # 실내 운동 위주

    # 8) 선호운동 → 카테고리 집계
    favorite_categories = []
    for fav in favorites_clean:
        cat = activity_to_category.get(fav)
        if cat:
            favorite_categories.append(cat)

    fav_cat_counter = Counter(favorite_categories)  # 예: {"유산소": 1, "구기스포츠": 1, ...}

    # 9) 후보 카테고리들에 대해 점수 계산 (선호 + 환경 + 공기질)
    candidate_cats = set(favorite_categories)
    candidate_cats.add(env_category)
    if pm_preferred_category:
        candidate_cats.add(pm_preferred_category)

    best_cat = env_category
    best_score = -1

    for cat in candidate_cats:
        score = 0
        # 선호 개수만큼 가산
        score += fav_cat_counter.get(cat, 0)
        # 환경 모델이 뽑은 카테고리와 일치하면 +1
        if cat == env_category:
            score += 1
        # 공기질 기준 우선 카테고리와 일치하면 +1
        if pm_preferred_category and cat == pm_preferred_category:
            score += 1

        if score > best_score:
            best_score = score
            best_cat = cat

    final_category = best_cat

    # 10) 해당 카테고리 내 후보 운동 필터링
    candidates = activity_df[activity_df["category"] == final_category].copy()

    # 계절 필터
    if "season" in candidates.columns:
        filtered = candidates[
            candidates["season"].isna()
            | candidates["season"].astype(str).str.contains(season_str)
        ]
        if not filtered.empty:
            candidates = filtered

    # 시간대 필터
    if "time_range" in candidates.columns:
        filtered = candidates[
            candidates["time_range"].isna()
            | candidates["time_range"].astype(str).str.contains(time_range_str)
        ]
        if not filtered.empty:
            candidates = filtered

    # 11) 최종 운동 선택 로직
    reason_parts = []

    if favorites_clean:
        reason_parts.append(f"사용자 선호운동(실시간 입력): {favorites_clean}")

    # 1순위: 선호운동 중에서 현재 카테고리 + 필터를 만족하는 운동
    matched_favs = [
        fav for fav in favorites_clean
        if fav in candidates["activity_name"].values
    ]

    if matched_favs:
        chosen_activity = matched_favs[0]
        reason_parts.append(
            f"선호운동 중에서 현재 카테고리/조건에 맞는 운동을 우선 추천했습니다: {matched_favs}"
        )
    else:
        # 2순위: 그냥 후보 중에서 랜덤
        if candidates.empty:
            # 혹시 필터링하다가 비면, 같은 카테고리 전체에서 랜덤
            candidates = activity_df[activity_df["category"] == final_category]
        if candidates.empty:
            chosen_activity = None
            reason_parts.append("해당 조건에 맞는 운동을 찾지 못했습니다.")
        else:
            row = candidates.sample(1).iloc[0]
            chosen_activity = row["activity_name"]
            reason_parts.append("선호운동과 정확히 일치하는 후보가 없어, 카테고리 내 운동 중 하나를 무작위로 추천했습니다.")

    # 공기질 설명 추가
    if pm_preferred_category == "피트니스":
        reason_parts.append("미세먼지·초미세먼지 수치가 높아 실내 운동(피트니스)을 우선 고려했습니다.")

    return {
        "입력값": {
            "user_id": req.user_id,
            "location_name": req.location_name,
            "target_datetime": req.target_datetime.isoformat(),
            "favorites_from_request": favorites_clean,
        },
        "지오코딩": {
            "위도": lat,
            "경도": lon,
        },
        "사용된_날씨": {
            "temperature": forecast["temperature"],
            "humidity": forecast["humidity"],
            "wind_speed": forecast["wind_speed"],
            "precipitation": forecast["precipitation"],
            "pm25": pm25,
            "pm10": pm10,
            "pm_grade": pm_grade,
            "season": season_str,
            "time_range": time_range_str,
            "owm_dt_txt": forecast["owm_dt_txt"],
        },
        "예측_카테고리_원본": env_category,
        "실제_사용_카테고리": final_category,
        "추천_운동": chosen_activity,
        "추천_근거": " / ".join(reason_parts),
        "디버그": {
            "favorite_categories_counter": dict(fav_cat_counter),
            "pm_preferred_category": pm_preferred_category,
        },
    }