# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15xUsIc96lG4x4uuG39sa5PhoT7xVnVjz
"""

# app.py

from fastapi import FastAPI
from pydantic import BaseModel
from typing import List, Optional
from datetime import datetime
import requests
import pandas as pd
import joblib

# =========================
# 🔧 설정 – OpenWeatherMap
# =========================
OWM_API_KEY = "9f8737894290204a7b2793f510443e46"  # 👉 여기 본인 API 키 넣기
OWM_GEOCODE_URL = "http://api.openweathermap.org/geo/1.0/direct"
OWM_FORECAST_URL = "https://api.openweathermap.org/data/2.5/forecast"       # 5일 / 3시간 예보
OWM_AIR_URL = "http://api.openweathermap.org/data/2.5/air_pollution"        # 현재 대기질

# =========================
# 🎯 학습된 모델/스케일러/인코더 로드
# =========================
category_model = joblib.load("category_model.pkl")
scaler = joblib.load("feature_scaler.pkl")
le_category = joblib.load("category_label_encoder.pkl")

# =========================
# 📂 CSV 로드 (운동 메타데이터)
# =========================
activity_df = pd.read_csv("activity_information.csv")
activity_df = activity_df.rename(
    columns={
        "활동명": "activity_name",
        "활동카테고리": "category",
        "장소유형": "location_type",
        "난이도": "difficulty",
        "추천계절": "season",
        "적합시간대": "time_range",
    }
)

season_map = {"봄": 0, "여름": 1, "가을": 2, "겨울": 3}

# =========================
# 🧩 Pydantic 요청 스키마
# =========================
class LocationUserRequest(BaseModel):
    user_id: str
    location_name: str
    target_datetime: datetime
    favorites: Optional[List[str]] = None  # ✅ UI에서 실시간으로 받은 선호운동 리스트


# =========================
# 🔧 계절 / 시간대 유틸
# =========================
def get_season_from_month(m: int) -> str:
    if 3 <= m <= 5:
        return "봄"
    if 6 <= m <= 8:
        return "여름"
    if 9 <= m <= 11:
        return "가을"
    return "겨울"


def get_time_range_from_hour(h: int) -> str:
    if 5 <= h < 12:
        return "오전"
    if 12 <= h < 18:
        return "오후"
    if 18 <= h < 23:
        return "저녁"
    return "야간"


def classify_pm(pm25: float, pm10: float) -> str:
    # 간단 한국 환경 기준 근사 버전
    if pm25 <= 15 and pm10 <= 30:
        return "좋음"
    if pm25 <= 35 and pm10 <= 80:
        return "보통"
    if pm25 <= 75 and pm10 <= 150:
        return "나쁨"
    return "매우 나쁨"


# =========================
# 🌍 Geocoding – OpenWeatherMap + Fallback
# =========================
def geocode_owm(location_name: str):
    """
    OpenWeatherMap Geocoding.
    - 1차: 그대로 location_name으로 검색
    - 2차: ",KR" 붙여서 검색
    - 3차: '성남시 수정구' → '성남시' 같은 도시 단위로 축약해서 재시도
    """

    def call_geocode(q: str):
        params = {
            "q": q,
            "limit": 1,
            "appid": OWM_API_KEY,
        }
        r = requests.get(OWM_GEOCODE_URL, params=params)
        r.raise_for_status()
        return r.json()

    queries = []

    # 1) 원본 그대로
    queries.append(location_name)
    queries.append(f"{location_name},KR")

    # 2) '성남시 수정구' → '성남시' 같은 형태로 축약
    tokens = location_name.split()
    if tokens:
        city_token = None
        for t in tokens:
            if t.endswith("시"):
                city_token = t
                break
        if city_token is None:
            city_token = tokens[0]

        queries.append(city_token)
        queries.append(f"{city_token},KR")

    # 실제 호출 시도
    for q in queries:
        try:
            data = call_geocode(q)
        except Exception:
            continue

        if data:
            lat = float(data[0]["lat"])
            lon = float(data[0]["lon"])
            return lat, lon

    # 전부 실패하면 에러
    raise ValueError(
        f"'{location_name}' 에 대한 좌표를 OpenWeatherMap에서 찾지 못했습니다. "
        f"도시 이름만(예: '성남시' 또는 'Seongnam-si')으로 다시 시도해 보세요."
    )


# =========================
# 🌦 OpenWeather 5일 예보 + 1시간 간격 보간 + Air Pollution
# =========================
def get_weather_from_owm(lat: float, lon: float, target_dt: datetime):
    # 1) 5일 / 3시간 예보
    params = {
        "lat": lat,
        "lon": lon,
        "appid": OWM_API_KEY,
        "units": "metric",
        "lang": "kr",
    }
    r = requests.get(OWM_FORECAST_URL, params=params)
    r.raise_for_status()
    data = r.json()

    items = data.get("list", [])
    if not items:
        raise RuntimeError("OpenWeather 5일 예보 데이터를 가져오지 못했습니다.")

    rows = []
    for it in items:
        dt_txt = it.get("dt_txt")
        if not dt_txt:
            continue

        main = it.get("main", {})
        wind = it.get("wind", {})
        rain = it.get("rain", {})

        temp = main.get("temp")
        hum = main.get("humidity")
        ws = wind.get("speed", 0.0)
        precip = rain.get("3h", 0.0) or 0.0

        rows.append(
            {
                "dt": pd.to_datetime(dt_txt),
                "temperature": float(temp) if temp is not None else None,
                "humidity": float(hum) if hum is not None else None,
                "wind_speed": float(ws),
                "precipitation": float(precip),
            }
        )

    df = pd.DataFrame(rows).set_index("dt").sort_index()

    # ✅ 3시간 → 1시간으로 resample (이전 값 유지)
    df_1h = df.resample("1H").ffill()

    # target_dt가 범위 밖이면 가장 가까운 시점으로 보정
    if target_dt < df_1h.index.min():
        chosen_ts = df_1h.index.min()
    elif target_dt > df_1h.index.max():
        chosen_ts = df_1h.index.max()
    else:
        idx = df_1h.index.get_indexer([target_dt], method="nearest")[0]
        chosen_ts = df_1h.index[idx]

    row = df_1h.loc[chosen_ts]

    # 2) 대기질 (현재값 사용 – 단순화)
    air_params = {
        "lat": lat,
        "lon": lon,
        "appid": OWM_API_KEY,
    }
    air_r = requests.get(OWM_AIR_URL, params=air_params)
    pm25 = 0.0
    pm10 = 0.0
    try:
        air_r.raise_for_status()
        air_data = air_r.json()
        first = air_data.get("list", [{}])[0]
        comps = first.get("components", {})
        pm25 = float(comps.get("pm2_5", 0.0))
        pm10 = float(comps.get("pm10", 0.0))
    except Exception:
        pm25 = 0.0
        pm10 = 0.0

    return {
        "temperature": float(row["temperature"]),
        "humidity": float(row["humidity"]),
        "wind_speed": float(row["wind_speed"]),
        "precipitation": float(row["precipitation"]),
        "pm25": pm25,
        "pm10": pm10,
        "raw_dt": chosen_ts.strftime("%Y-%m-%d %H:%M:%S"),
    }


# =========================
# 🚀 FastAPI 앱
# =========================
app = FastAPI(
    title="OpenWeather 기반 AI 운동 추천 API",
    description="위치 + 시간 + 실시간 선호운동 + 날씨/미세먼지로 최적 운동 추천",
    version="1.0",
)


@app.get("/")
def home():
    return {"message": "운동 추천 API 작동 중!"}


# =========================
# 🧠 핵심 엔드포인트
# =========================
@app.post("/recommend/by-location-and-user")
def recommend_by_location_and_user(req: LocationUserRequest):
    # 1) 위치 → 위/경도
    lat, lon = geocode_owm(req.location_name)

    # 2) 해당 시점의 날씨 + 대기질
    weather = get_weather_from_owm(lat, lon, req.target_datetime)

    # 3) 계절 / 시간대 / season_code
    season_str = get_season_from_month(req.target_datetime.month)
    time_range_str = get_time_range_from_hour(req.target_datetime.hour)
    season_code = season_map.get(season_str, -1)

    # 4) XGBoost 입력 만들기 (날씨 기반 카테고리 예측용)
    feature_cols = [
        "temperature",
        "humidity",
        "wind_speed",
        "precipitation",
        "pm25",
        "season_code",
    ]
    raw_features = [
        weather["temperature"],
        weather["humidity"],
        weather["wind_speed"],
        weather["precipitation"],
        weather["pm25"],
        season_code,
    ]
    scaled = scaler.transform([raw_features])
    X_input = pd.DataFrame(scaled, columns=feature_cols)

    # 5) XGBoost가 예측한 카테고리 (날씨 기반)
    model_cat_id = category_model.predict(X_input)[0]
    model_cat = le_category.inverse_transform([model_cat_id])[0]

    # 6) 미세먼지 + 날씨 상태 평가 → 실내/실외 결정
    temp = weather["temperature"]
    ws = weather["wind_speed"]
    precip = weather["precipitation"]
    pm25 = weather["pm25"]
    pm10 = weather["pm10"]
    pm_grade = classify_pm(pm25, pm10)

    # 비, 강풍, 너무 춥거나 더우면 "밖에 나가기 안 좋은 날씨"로 간주
    is_rainy = precip > 0.0
    is_windy = ws >= 8.0         # 2~3단계 이상 바람
    is_too_cold = temp <= 0.0
    is_too_hot = temp >= 30.0
    is_bad_weather = is_rainy or is_windy or is_too_cold or is_too_hot

    # 공기 안 좋음
    is_bad_air = pm_grade in ["나쁨", "매우 나쁨"]

    # 최종적으로 실내를 강하게 추천해야 하는지 여부
    indoor_required = is_bad_weather or is_bad_air

    # 7) 선호운동(favorites) 정제 + 카테고리 조회
    fav_list_raw = req.favorites or []
    fav_list = [
        f.strip().replace(",", "")
        for f in fav_list_raw
        if f and f.strip()
    ]

    fav_meta = activity_df[activity_df["activity_name"].isin(fav_list)].copy()
    fav_cats = list(fav_meta["category"].unique())

    reason_parts = []
    if fav_list:
        reason_parts.append(f"사용자 선호운동(실시간 입력): {fav_list}")
    else:
        reason_parts.append("선호운동이 전달되지 않아, 모델이 예측한 카테고리를 사용했습니다.")

    # 8) 카테고리 선택 로직 (선호운동 + XGBoost + 실내/실외 조건)
    if fav_cats:
        # 8-1) 선호운동 카테고리가 하나뿐이면 그걸 기본으로
        if len(fav_cats) == 1:
            base_cat = fav_cats[0]
            reason_parts.append(f"두 선호운동의 카테고리가 동일하여 '{base_cat}' 카테고리를 우선 사용했습니다.")
        else:
            # 두 개 이상인 경우
            if model_cat in fav_cats:
                base_cat = model_cat
                reason_parts.append(
                    f"XGBoost가 예측한 카테고리 '{model_cat}' 가 선호운동 카테고리 중 하나여서 이를 우선 사용했습니다."
                )
            else:
                base_cat = fav_cats[0]
                reason_parts.append(
                    f"선호운동 카테고리가 서로 달라, 그 중 첫 번째 카테고리 '{base_cat}' 를 기본으로 사용했습니다."
                )
        pred_category = base_cat
    else:
        # 선호운동이 매핑되지 않으면 → 모델 카테고리 사용
        pred_category = model_cat
        reason_parts.append(
            f"선호운동이 활동 목록과 매칭되지 않아, XGBoost가 예측한 카테고리 '{model_cat}' 를 사용했습니다."
        )

    # 9) 실내/실외 우선 규칙 설명
    if indoor_required:
        reason_parts.append(
            f"날씨/대기 상태가 좋지 않아(비:{is_rainy}, 강풍:{is_windy}, 추움:{is_too_cold}, 더움:{is_too_hot}, 미세먼지등급:{pm_grade}), 실내 운동을 우선 고려했습니다."
        )
    else:
        reason_parts.append(
            f"날씨와 공기 질이 비교적 양호하여, 실외 운동을 우선 고려했습니다."
        )

    # 10) 최종 카테고리에 속하는 후보 운동들 필터링
    candidates = activity_df[activity_df["category"] == pred_category].copy()

    # 계절 필터
    cand_season = candidates[
        (candidates["season"].isna())
        | (candidates["season"].astype(str).str.contains(season_str))
    ]
    if not cand_season.empty:
        candidates = cand_season

    # 시간대 필터
    cand_time = candidates[
        (candidates["time_range"].isna())
        | (candidates["time_range"].astype(str).str.contains(time_range_str))
    ]
    if not cand_time.empty:
        candidates = cand_time

    # ✅ 실내/실외 필터 적용
    if indoor_required:
        # 실내 우선
        indoor_cands = candidates[
            candidates["location_type"].astype(str).str.contains("실내")
        ]
        if not indoor_cands.empty:
            candidates = indoor_cands
    else:
        # 실외 우선
        outdoor_cands = candidates[
            candidates["location_type"].astype(str).str.contains("실외")
        ]
        if not outdoor_cands.empty:
            candidates = outdoor_cands

    if candidates.empty:
        # 만약 위 필터로 다 날아가면 -> 카테고리만 맞는 전체 후보로 복구
        candidates = activity_df[activity_df["category"] == pred_category].copy()

    # 11) 최종 운동 선택: 카테고리 + (실내/실외) 안에서 선호운동 우선
    recommended_activity = None
    fav_match_list: List[str] = []

    if fav_list:
        fav_in_cat = candidates[candidates["activity_name"].isin(fav_list)]
        if not fav_in_cat.empty:
            chosen = fav_in_cat.sample(1).iloc[0]
            recommended_activity = chosen["activity_name"]
            fav_match_list = list(fav_in_cat["activity_name"].unique())
            reason_parts.append(
                f"선택된 카테고리/실내·실외 조건 안에서 선호운동과 일치하는 운동을 우선 추천했습니다: {fav_match_list}"
            )

    if recommended_activity is None:
        chosen = candidates.sample(1).iloc[0]
        recommended_activity = chosen["activity_name"]
        reason_parts.append(
            f"선호운동과 정확히 일치하는 항목이 없어, 선택된 카테고리/실내·실외 조건 안에서 운동을 무작위로 추천했습니다."
        )

    reason = " / ".join(reason_parts)

    return {
        "입력값": {
            "user_id": req.user_id,
            "location_name": req.location_name,
            "target_datetime": req.target_datetime.isoformat(),
            "favorites_from_request": fav_list,
        },
        "지오코딩": {"위도": lat, "경도": lon},
        "사용된_날씨": {
            "temperature": temp,
            "humidity": weather["humidity"],
            "wind_speed": ws,
            "precipitation": precip,
            "pm25": pm25,
            "pm10": pm10,
            "pm_grade": pm_grade,
            "season": season_str,
            "time_range": time_range_str,
            "owm_dt_txt": weather["raw_dt"],
            "is_rainy": is_rainy,
            "is_windy": is_windy,
            "is_too_cold": is_too_cold,
            "is_too_hot": is_too_hot,
            "is_bad_air": is_bad_air,
        },
        "XGBoost_예측_카테고리": model_cat,
        "최종_선택_카테고리": pred_category,
        "실내_우선여부": indoor_required,
        "추천_운동": recommended_activity,
        "추천_근거": reason,
        "디버그": {
            "favorites_raw": fav_list_raw,
            "favorites_clean": fav_list,
            "favorite_categories": fav_cats,
            "favorites_matched_in_category": fav_match_list,
        },
    }