# -*- coding: utf-8 -*-
"""build_graph_for_gnn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nPLxtP34jt5LOY80jSOuK0-Rl5b2Bw1t
"""

import pandas as pd
import torch
import numpy as np

# 1) 데이터 로드
users = pd.read_csv("user_preference.csv")      # UserID, 선호운동1, 선호운동2, ...
acts  = pd.read_csv("activity_information.csv") # 활동명, 활동카테고리, ...

acts = acts.rename(columns={"활동명": "activity_name"})

# 2) ID 매핑
user_ids = users["UserID"].astype(str).unique()
act_names = acts["activity_name"].astype(str).unique()

user2idx = {u: i for i, u in enumerate(user_ids)}
act2idx  = {a: i for i, a in enumerate(act_names)}

num_users = len(user2idx)
num_acts  = len(act2idx)

# 3) user-preference → edge list (user, activity)
edges_u = []
edges_a = []

for _, row in users.iterrows():
    u = user2idx[str(row["UserID"])]
    for col in ["선호운동1", "선호운동2"]:
        if col in row and isinstance(row[col], str) and row[col] in act2idx:
            a = act2idx[row[col]]
            # user node index = u
            # activity node index = num_users + a  (한 그래프에 합쳐버리기)
            edges_u.append(u)
            edges_a.append(num_users + a)

edge_index = torch.tensor([edges_u, edges_a], dtype=torch.long)

print("num_users:", num_users)
print("num_acts:", num_acts)
print("num_edges:", edge_index.size(1))

torch.save(
    {
        "edge_index": edge_index,
        "num_users": num_users,
        "num_acts": num_acts,
        "user2idx": user2idx,
        "act2idx": act2idx,
    },
    "gnn_graph_data.pt",
)
print("✅ gnn_graph_data.pt 저장 완료")