# -*- coding: utf-8 -*-
"""train_category_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mq3_WaDona8fBLf8j-oHV_OU4a08Wfyj
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, LabelEncoder
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, f1_score
import joblib

# 1️⃣ 날씨 데이터 로드
weather = pd.read_csv("Weather_Conditions.csv")

# 2️⃣ 컬럼 정리
weather = weather.rename(
    columns={
        "기온(°C)": "temperature",
        "습도(%)": "humidity",
        "풍속(m/s)": "wind_speed",
        "강수량(mm)": "precipitation",
        "Air_PM2.5_수치": "pm25",
        "날짜시간": "dt",
    }
)

# 날짜 파싱
weather["dt"] = pd.to_datetime(weather["dt"], errors="coerce")
weather = weather.dropna(subset=["dt"])

# 기본 결측치 처리
for col in ["temperature", "humidity", "wind_speed", "precipitation", "pm25"]:
    if col in weather.columns:
        weather[col] = weather[col].fillna(0)

# 3️⃣ 계절 코드 (app.py와 맞추기 위함)
def get_season_from_month(m: int) -> str:
    if 3 <= m <= 5:
        return "봄"
    if 6 <= m <= 8:
        return "여름"
    if 9 <= m <= 11:
        return "가을"
    return "겨울"

season_map = {"봄": 0, "여름": 1, "가을": 2, "겨울": 3}
weather["season_str"] = weather["dt"].dt.month.apply(get_season_from_month)
weather["season_code"] = weather["season_str"].map(season_map)

# 4️⃣ 규칙 기반 카테고리 생성 함수
def weather_to_category(row):
    t = row["temperature"]
    h = row["humidity"]
    w = row["wind_speed"]
    p = row["precipitation"]
    pm = row["pm25"]

    # ❌ 나쁜 환경 → 실내 피트니스
    if p >= 1.0 or t <= 0 or t >= 33 or pm >= 50:
        return "피트니스"

    # 💨 바람이 꽤 불고, 따뜻한 편 → 익스트림스포츠 (서핑, MTB 같은 느낌)
    if 15 <= t <= 30 and w >= 4:
        return "익스트림스포츠"

    # 🤝 적당한 온도, 적당한 바람 → 구기스포츠 (축구, 농구 등)
    if 12 <= t <= 28 and 1 <= w < 4 and h <= 75:
        return "구기스포츠"

    # 🚶‍♂️ 나머지 야외 상황 → 유산소 (걷기, 조깅 등)
    return "유산소"


# 5️⃣ 규칙으로 y 생성
weather["category"] = weather.apply(weather_to_category, axis=1)

print("규칙으로 생성된 카테고리 분포:")
print(weather["category"].value_counts())

# 6️⃣ 입력 피처 / 타깃 구성
numeric_cols = ["temperature", "humidity", "wind_speed", "precipitation", "pm25"]
feature_cols = numeric_cols + ["season_code"]

# 혹시라도 누락된 컬럼이 있으면 0으로 채움
for col in numeric_cols:
    if col not in weather.columns:
        weather[col] = 0.0

X = weather[feature_cols].copy()
y = weather["category"].astype(str)

# 7️⃣ 스케일링
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

# 8️⃣ 타깃 인코딩
le_category = LabelEncoder()
y_encoded = le_category.fit_transform(y)

# 9️⃣ train / test split
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled,
    y_encoded,
    test_size=0.2,
    random_state=42,
    stratify=y_encoded,
)

# 🔟 클래스 가중치 (혹시 불균형 시 조금 보정)
class_counts = pd.Series(y_train).value_counts()
class_weight = {
    cls: len(y_train) / (len(class_counts) * cnt)
    for cls, cnt in class_counts.items()
}
sample_weights = np.array([class_weight[cls] for cls in y_train])

# 1️⃣1️⃣ XGBoost 모델 정의
model = XGBClassifier(
    objective="multi:softmax",
    learning_rate=0.05,
    max_depth=6,
    n_estimators=300,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
)

# 1️⃣2️⃣ 학습
model.fit(X_train, y_train, sample_weight=sample_weights)

# 1️⃣3️⃣ 평가
y_pred = model.predict(X_test)
acc = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average="weighted")

print("✅ Rule-based Category Accuracy:", acc)
print("✅ Rule-based Category F1 Score:", f1)

# 1️⃣4️⃣ 저장 (app.py가 이 파일들을 사용)
joblib.dump(model, "category_model.pkl")
joblib.dump(scaler, "feature_scaler.pkl")
joblib.dump(le_category, "category_label_encoder.pkl")
print("🎯 규칙 기반 카테고리 모델 저장 완료!")